### ISSUE TITLE
This is a very important project, why it is being abandoned?

### ISSUE THREAD

**Issue by Emasoft** [mono/sysdrawing-coregraphics#12]
This is a very important project, why it is being abandoned? Not only it is still incomplete, but it has not been migrated to the 64 bit stack necessary to make crossplatform applications on OS X, iOS, Android, Linux and Windows Phone using the same System.Drawing calls.

**Comment by chamons** [comment]
@Emasoft This is a project under mono/, and thus a community project, so I would not call it abandoned.

A few updates:

- The implementation uses CoreGraphics under the hood (part of the project name), and thus requires CoreGraphics, which is an Apple specific technology.
- We just merged work to update it to build against Xamarin.Mac / Xamarin.iOS Unified.
