### ISSUE TITLE
missing simple classes, needed for MonoMac.Windows.Form

### ISSUE THREAD

**Issue by HinTak** [mono/sysdrawing-coregraphics#16]
MonoMac.Windows.Form ( git://github.com/Clancey/MonoMac.Windows.Form.git ) looks interesting, and seems to try to do similar thing as sysdrawing-coregraphics. It seems to be earlier, and depends on mono's system.drawing. So I tried switching it over to sysdrawing-coregraphics , and found that sysdrawing-coregraphics is missing a few simple classes:

```
Color' could not be found. Are you missing an assembly reference?
Color' does not exist in the namespace `System.Drawing'. Are you missing an assembly reference?
ContentAlignment' could not be found. Are you missing an assembly reference?
Design' does not exist in the namespace `System.Drawing'. Are you missing an assembly reference?
Point' could not be found. Are you missing an assembly reference?
PointF' does not exist in the namespace `System.Drawing'. Are you missing an assembly reference?
Rectangle' could not be found. Are you missing an assembly reference?
RectangleF' could not be found. Are you missing an assembly reference?
RectangleF' does not exist in the namespace `System.Drawing'. Are you missing an assembly reference?
Size' could not be found. Are you missing an assembly reference?
Size' does not exist in the namespace `System.Drawing'. Are you missing an assembly reference?
SizeF' could not be found. Are you missing an assembly reference?
SizeF' does not exist in the namespace `System.Drawing'. Are you missing an assembly reference?
```

I looked at the usage of Design, and it seems to be not needed. The other should be a simple copy from mono's system.drawing ?

**Comment by HinTak** [comment]
I was able to resolve all the missing references by just copying these

```
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/PointF.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/Point.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/Rectangle.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/RectangleF.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/ContentAlignment.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/Color.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/Size.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/SizeF.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing/KnownColor.cs" />
    <Compile Include="../github.com/mono/mono/raw/master/mcs/class/System.Drawing/System.Drawing.Imaging/ColorPalette.cs" />
```

Into MonoMac.Windows.Form's build project. The rest of the errors seems to be API mismatch and some bitrot.

**Comment by chamons** [comment]
So those classes are generally provided by Xamarin.Mac (or OpenTK.dll for XM 4.5 target framework). You are welcome to fork and provide your own special build, but we can't accept this since it will break Xamarin.Mac users.

Are you trying to use MonoMac.Windows.Form without Xamarin.Mac?

**Comment by HinTak** [comment]
I was building against xamarin mac. Are the missing system.drawing classes in opentk? That's very confusing.

**Comment by chamons** [comment]
Yes, if you are using the 4.5 target framework:

$ monop -r:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Xamarin.Mac.dll | grep System.Drawing.Point
System.Drawing.Point
System.Drawing.PointF
$ monop -r:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/4.5/Xamarin.Mac.dll | grep System.Drawing.Point
$ monop -r:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/4.5/OpenTK.dll | grep System.Drawing.Point
System.Drawing.Point
System.Drawing.PointF

which is rather :( that the type is provided in a different location in XM.45 than Mobile. However, due to backwards compatibility, I am unable to change this very easily.

**Comment by HinTak** [comment]
That's an user's expectation issue - I did grep through the source of xamarin-macios after I filed, and found that oddity of putting System.Drawing.* classes elsewhere in an entirely different assembly; and only half of it. I was already linking in Xamarin.Mac (which is expected for coregraphics), but wasn't expecting to have to bring in OpenTK.dll.

How about putting those extra classes in a System.Drawing.mini.dll or some name of that sort, and have Xamarin.Mac.dll and OpenK.dll bring in that little extra?

In any case, MonoMac.Windows.Form seems to be a good companion to sysdrawing-coregraphics and possibly worth say, adding a bit of extra build tips documentation somewhere. I am still trying to fix bit-rot at the moment, Xamarin.mac/MonoMac has changed in the 5 years since. Would be nice to build simple winform apps for mac os look-and-feel by just re-linking with both of these.

**Comment by HinTak** [comment]
BTW, the last two of the list (knowncolor and colorpalatte) was indirect references. i.e. maybe I don't need them if I can hack at the Color.cs class or have a different one.

**Comment by migueldeicaza** [comment]
I am now merging these changes.

**Comment by filipnavara** [comment]
Maybe we can close this now?

**Comment by migueldeicaza** [comment]
Closing!
