### ISSUE TITLE
How to use it in a Xamarin/Visual Studio MAC app

### ISSUE THREAD

**Issue by midiway** [mono/sysdrawing-coregraphics#20]
I create a Cocoa/C# based app with the wizard template from Visual Studio MAC 2017, then import the source from this repo. But compiling gives me a ton of errors.

Wasn't this lib created for this particular scenario: MONO based apps for MAC?

How to use or compile it? (tried make too, gives error)

No NuGeT?

**Comment by chamons** [comment]
Did you follow the instructions in the README:

> The Makefile assumes you have a copy of mono checked out side by side. You can update the MONO_SYSD variable to point to a checkout in another location if necessary.
> 
> To Build:
> 
> make
> 
> output will be found in top level bin directory.

See https://forums.xamarin.com/discussion/comment/263406/#Comment_263406 as well.
