### ISSUE TITLE
Example does not compile in latest Xamarin MonoMac

### ISSUE THREAD

**Issue by JoeStrout** [mono/sysdrawing-coregraphics#9]
Trying to compile DrawStringTest, I get this error:

.../sysdrawing-coregraphics/Samples/MonoMac/DrawStringTest/DrawingView.cs(33,33): Error CS1729: The type `System.Drawing.Graphics' does not contain a constructor that takes `0' arguments (CS1729) (DrawStringTest)

Note that the project initially didn't get even this far, because the "using System.Drawing" line failed since System.Drawing wasn't included in the references.  So I added it.  But now I wonder whether I added the wrong thing.

So possible the real problem here is that the README.md needs to include instructions on how to use this library, for newbies like me?

**Comment by kjpou1** [comment]
This has now been implemented in the unified branch and will be moved to master soon.  Will mark this as closed.
